package model;

public class Survey {
    private int id;          // Auto-generated by DB
    private String username; // Creator's username instead of creator_id
    private String title;
    private String description;
    private String startDate;
    private String endDate;
    private String status;   // Consider using enum in future

    // Constructor for new surveys (without ID)
    public Survey(String username, String title, String description,
                  String startDate, String endDate, String status) {
        this.username = username;
        this.title = title;
        this.description = description;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
    }

    // Constructor for existing surveys (with ID)
    public Survey(int id, String username, String title, String description,
                  String startDate, String endDate, String status) {
        this(username, title, description, startDate, endDate, status);
        this.id = id;
    }

    // --- Getters & Setters ---
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getStartDate() { return startDate; }
    public void setStartDate(String startDate) { this.startDate = startDate; }

    public String getEndDate() { return endDate; }
    public void setEndDate(String endDate) { this.endDate = endDate; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
}
